[package]
name = "contracts"
version = "0.2.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.4"
openzeppelin_access = "2.0.0"
openzeppelin_token = "2.0.0"
openzeppelin_introspection = "2.0.0"

[dev-dependencies]
openzeppelin_utils = "2.0.0"
openzeppelin_testing = "4.3.0"
snforge_std = "0.46.0"
assert_macros = "2.9.4"

[[target.starknet-contract]]
casm = true

[tool]
panic-backtrace = true

  [tool.scarb]
  allow-prebuilt-plugins = [ "snforge_std" ]

  [tool.fmt]
  sort-module-level-items = true

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8"

  [tool.snforge.fork.block_id]
  tag = "latest"